### PR TITLE
Add basic support for properties

### PR DESCRIPTION
**Pull request by marceldev89**
Added basic support for properties that are added during runtime (e.g. CakePHP adds properties to controllers that reference models/helpers/etc). This was briefly talked about in https://github.com/shawncplus/phpcomplete.vim/issues/82#issuecomment-164427817 and I figured I'd give it a try.

_This pull request is more about getting my changes reviewed than getting it merged. It's my first ever adventure in vim plugins/scripting so there's probably a lot that's not how it's supposed to be done._ :smile:

### CODE REVIEW

**Comment by lvht** [comment]
May be you @marceldev89  should try the https://github.com/phpvim/phpcd.vim . A new phpcomplete extended version based on the PHP's Reflection.

**Comment by complex857** [comment]
@marceldev89 Thank you for spending the time and effort to write the code.
As you most certainly know, the main thing that needed to be done is to make the class-content-grabbing process return the docblock for the classes (the `@property` comments are usually resides outside of the class's code itself).

I'll try to write a few test's for your code so we can be sure that it continues to work as intended.

>  It's my first ever adventure in vim plugins/scripting

Welcome to the herd (-:

**Comment by complex857** [comment]
I've merged and pushed your code with one feature addition (made `@property` stuff [show up](https://github.com/shawncplus/phpcomplete.vim/commit/d2bbaf159a44abba266ef38abec89fb9cfaec69c) in the class completions) and with tests so that they should be somewhat safe against regressions and have a baseline for later improvements.

Thank you again for the code, i really appreciate it and sorry for the delay.

**Comment by marceldev89** [comment]
Awesome! :smile:

**Pull request merged**
